# Source: mariadb-operator/templates/operator/configmap.yaml
apiVersion: v1
data:
  MARIADB_OPERATOR_IMAGE: "docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:0.38.1"
  MARIADB_GALERA_LIB_PATH: "/usr/lib/galera/libgalera_smm.so"
  MARIADB_DEFAULT_VERSION: "11.4"
  RELATED_IMAGE_MARIADB: "docker-registry1.mariadb.com/library/mariadb:11.4.5"
  RELATED_IMAGE_MAXSCALE: "docker-registry2.mariadb.com/mariadb/maxscale:23.08.5"
  RELATED_IMAGE_EXPORTER: "prom/mysqld-exporter:v0.15.1"
  RELATED_IMAGE_EXPORTER_MAXSCALE: "docker-registry2.mariadb.com/mariadb/maxscale-prometheus-exporter-ubi:v0.0.1"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mariadb-operator-env
