# Source: mariadb-operator/templates/operator/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-operator-mmontes
  labels:
    helm.sh/chart: mariadb-operator-0.38.1
    app.kubernetes.io/name: mariadb-operator
    app.kubernetes.io/instance: mariadb-operator-mmontes
    app.kubernetes.io/version: "0.38.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb-operator
      app.kubernetes.io/instance: mariadb-operator-mmontes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb-operator
        app.kubernetes.io/instance: mariadb-operator-mmontes
    spec:
      serviceAccountName: mariadb-operator-mmontes
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 10
      containers:
        - image: "docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:0.38.1"
          imagePullPolicy: IfNotPresent
          name: controller
          args:
            - --metrics-addr=:8080
            - --log-level=INFO
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
          envFrom:
            - configMapRef:
                #name: mariadb-operator-env-x-mariadb-system-x-vcluster--slurm-dev
                name: mariadb-operator-env
          env:
            - name: CLUSTER_NAME
              value: cluster.local
            - name: MARIADB_OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: MARIADB_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MARIADB_OPERATOR_SA_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
